# Configuration file for SoupFFA
# SoupFFA by @McpeBooster

#If you need help, look at the ReadMe.md


#The SoupFFA Arena world here
arena: debug123

#The spawnprotecion radius, where PvP is disabled
spawnprotection: 5

#Kit for Normal Players
sword: 267
helmet: 298
chestplate: 303
leggings: 300
boots: 301

#Kit for Vip Players with the permission "soupffa.vip"
vipsword: 267
viphelmet: 302
vipchestplate: 303
vipleggings: 304
vipboots: 305